# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update The Planet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0  # all history for all branches and tags

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up git repository
      run: |
        git status
        git branch
        git checkout master
        git status

        # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        git config user.name "macbrebot"
        git config user.email "<51094006+macbrebot@users.noreply.github.com>"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update The Planet
      run: make

    - name: Commit changes
      run: |
        git diff
        git add docs/ && git commit -m 'Updating the Planet via GitHub Actions'
        # git push origin master
